### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by fklirono** [PacificBiosciences/pbmm2#3]
Hello,
I am getting a compilation error with pbmm2 v0.4.0. 
meson version 0.47.1
htslib version 1.9
ninja version 1.5.1
I have attached the full error log. Any help how to solve this would be greatly appreciated.

[error.log](https://github.com/PacificBiosciences/pbmm2/files/2273341/error.log)

**Comment by armintoepfer** [comment]
Your GCC is too old.

**Comment by fklirono** [comment]
Thanks! I upgraded to gcc-7 and the error is gone!
