### ISSUE TITLE
Reg: Sorting the alignments and unsupported chemistry

### ISSUE THREAD

**Issue by harish0201** [PacificBiosciences/pbmm2#4]
Hi!

I have tried this tools today and I have to say it's stupid how fast is it compared with Blasr.

However, I'm trying to run Arrow after sorting the Bam, and reindexing using pbindex. 

I have been getting the following error: 

> Arrow:  unsupported chemistries found: (unknown)

Supporting the sorting would be immensely helpful. I have tried reheadering the sorted bam from a previously aligned blasr run but it seems to not have worked.

**Comment by armintoepfer** [comment]
Can you run GenomicConsensus successfully on the blasr alignment? And if yes, share an small example that fails on pbmm2, but succeeds on blasr? Please provide the exact commands you would run for the toy example.

**Comment by harish0201** [comment]
Unfortunately, the blasr alignments have been running for over a week, so I haven't had the chance to test it, to be honest. 

I can provide them once it finishes.

However, this is how I'm currently running pbmm2, on two smrtcell datasets. The bams for the two were merged using pbmerge.

`pbmerge -o merged.bam bam.fofn`
`pbmm2 -j 16 --pbi merged.bam clean.fasta aligned.bam`

The header in this case is:
`@HD	VN:1.5	SO:unknown	pb:3.0.5
@SQ	SN:tig00000002	LN:127866	M5:6b4cbb052d13088c9809eaf03e25e325
@SQ	SN:tig00000003	LN:49006	M5:9a6a423d1e324fcde3c5fd9c96048db6
@SQ	SN:tig00000004	LN:55264	M5:ccbbcecb01316750b25d6f73057ec00d
@SQ	SN:tig00000005	LN:81196	M5:52764d27ea54342a99150718b4f64821
@SQ	SN:tig00000006	LN:75137	M5:ab4edb65768f0d9f3436c17d5f8acfec
.......
@RG	ID:2e359b2f	PL:PACBIO	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PU:m54166_180626_084002	PM:SEQUEL
@RG	ID:f760b141	PL:PACBIO	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PU:m54166_180627_072914	PM:SEQUEL
@PG	ID:baz2bam	PN:baz2bam	VN:5.1.0.26367	CL:/opt/pacbio/ppa-5.1.0/bin/baz2bam /data/pb/m54166_180626_084002.baz -o /data/pb/m54166_180626_084002 --metadata /data/pb/.m54166_180626_084002.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 3.750000 --adapters /data/pb/m54166_180626_084002.adapters.fasta --controlAdapters /data/pb/m54166_180626_084002.controls.adapters.fasta --controls /data/pb/m54166_180626_084002.controls.fasta 
@PG	ID:bazFormat	PN:bazformat	VN:1.3.0
@PG	ID:bazwriter	PN:bazwriter	VN:5.1.0.26367
@PG	ID:pbmerge-0.18.0	PN:pbmerge	VN:0.18.0
@PG	ID:pbmm2	PN:pbmm2	VN:0.4.0 (commit 4744c96)`


`sambamba sort -t 20 -o aligned.sorted.bam aligned.bam`

The header in this case is:

`@HD	VN:1.5	SO:coordinate
@SQ	SN:tig00000002	LN:127866	M5:6b4cbb052d13088c9809eaf03e25e325
@SQ	SN:tig00000003	LN:49006	M5:9a6a423d1e324fcde3c5fd9c96048db6
@SQ	SN:tig00000004	LN:55264	M5:ccbbcecb01316750b25d6f73057ec00d
@SQ	SN:tig00000005	LN:81196	M5:52764d27ea54342a99150718b4f64821
@SQ	SN:tig00000006	LN:75137	M5:ab4edb65768f0d9f3436c17d5f8acfec
.....
@RG	ID:2e359b2f	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PL:PACBIO	PU:m54166_180626_084002
@RG	ID:f760b141	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PL:PACBIO	PU:m54166_180627_072914
@PG	ID:baz2bam	PN:baz2bam	CL:/opt/pacbio/ppa-5.1.0/bin/baz2bam /data/pb/m54166_180626_084002.baz -o /data/pb/m54166_180626_084002 --metadata /data/pb/.m54166_180626_084002.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 3.750000 --adapters /data/pb/m54166_180626_084002.adapters.fasta --controlAdapters /data/pb/m54166_180626_084002.controls.adapters.fasta --controls /data/pb/m54166_180626_084002.controls.fasta 	VN:5.1.0.26367
@PG	ID:bazFormat	PN:bazformat	VN:1.3.0
@PG	ID:bazwriter	PN:bazwriter	VN:5.1.0.26367
@PG	ID:pbmerge-0.18.0	PN:pbmerge	VN:0.18.0
@PG	ID:pbmm2	PN:pbmm2	VN:0.4.0 (commit 4744c96)`

This throws an error stating pb key not found in the header or to the tune of that. Hence I reheader that, by adding it back in:

`@HD	VN:1.5	SO:unknown	pb:3.0.5` in a text file.

`samtools reheader header.txt aligned.sort.bam > aligned. head.bam`
`pbindex aligned.head.bam`

So, the header looks like this now:
`@HD	VN:1.5	SO:coordinate	pb:3.0.1
@SQ	SN:tig00000002	LN:127866	M5:6b4cbb052d13088c9809eaf03e25e325
@SQ	SN:tig00000003	LN:49006	M5:9a6a423d1e324fcde3c5fd9c96048db6
@SQ	SN:tig00000004	LN:55264	M5:ccbbcecb01316750b25d6f73057ec00d
@SQ	SN:tig00000005	LN:81196	M5:52764d27ea54342a99150718b4f64821
@SQ	SN:tig00000006	LN:75137	M5:ab4edb65768f0d9f3436c17d5f8acfec
.....
@RG	ID:2e359b2f	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PL:PACBIO	PU:m54166_180626_084002
@RG	ID:f760b141	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-365-900;SEQUENCINGKIT=101-309-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=80.000000	PL:PACBIO	PU:m54166_180627_072914
@PG	ID:baz2bam	PN:baz2bam	CL:/opt/pacbio/ppa-5.1.0/bin/baz2bam /data/pb/m54166_180626_084002.baz -o /data/pb/m54166_180626_084002 --metadata /data/pb/.m54166_180626_084002.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 3.750000 --adapters /data/pb/m54166_180626_084002.adapters.fasta --controlAdapters /data/pb/m54166_180626_084002.controls.adapters.fasta --controls /data/pb/m54166_180626_084002.controls.fasta 	VN:5.1.0.26367
@PG	ID:bazFormat	PN:bazformat	VN:1.3.0
@PG	ID:bazwriter	PN:bazwriter	VN:5.1.0.26367
@PG	ID:pbmerge-0.18.0	PN:pbmerge	VN:0.18.0
@PG	ID:pbmm2	PN:pbmm2	VN:0.4.0 (commit 4744c96)
@PG	ID:samtools	PN:samtools	PP:baz2bam	VN:1.7	CL:samtools reheader aligned.head aligned.sort.bam
@PG	ID:samtools.1	PN:samtools	PP:bazFormat	VN:1.7	CL:samtools reheader aligned.head aligned.sort.bam
@PG	ID:samtools.2	PN:samtools	PP:bazwriter	VN:1.7	CL:samtools reheader aligned.head aligned.sort.bam
@PG	ID:samtools.3	PN:samtools	PP:pbmerge-0.18.0	VN:1.7	CL:samtools reheader aligned.head aligned.sort.bam
@PG	ID:samtools.4	PN:samtools	PP:pbmm2	VN:1.7	CL:samtools reheader aligned.head aligned.sort.bam`

and reindexing using pbindex to run arrow:

`pbindex aligned. head.bam`

~/smrtlink/smrtcmds/bin/arrow -j 16 -r clean.fasta -o variants.gff -o cons.fq aligned.head.bam
`Arrow: unsupported chemistries found: (unknown)`

**Comment by pb-dseifert** [comment]
Arrow in SMRTlink requires enviromental variables to be set up to work for newer chemistries. Maybe give the new bioconda release a try: `conda install -c bioconda genomicconsensus`

**Comment by harish0201** [comment]
Awesome! Installing from BIoconda seems to have resolved the issue!

Does this mean that the entire PB suite of tools will be making their way eventually to bioconda?

**Comment by pb-dseifert** [comment]
Most of the secondary tools are on Bioconda. Some, but not the entire collection will be there. Be aware that these tools and Bioconda are a best effort service. We make *no guarantees* as to the validity of the outcomes, and if you need quality guarantees, you need to use SMRT Link.
