### ISSUE TITLE
Suggestion: allow piping e.g. to samtools or alternatively sorting of BAM

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/pbmm2#6]
thx for this initiative, very appreciated!
I was wondering whether you might want to consider either allowing piping the BAM stream or offer directly sorting it.
The motivation behind this is the use of the results for quiver/arrow which needs another round of sorting and indexing subsequently. As files can grow large for some organisms a sorting on the flow would be great.
Cheers

**Comment by armintoepfer** [comment]
Thank you for the feedback.

I'm currently brainstorming, if I should do the sorting or not. My personal preference is to let samtools handle it, with its sophisticated approach of in-memory and temp disk chunks. All I would do is in-memory sorting, that will blow out memory requirements once you align a 50x human dataset :)

I'll investigate, if I can use pbbam to write to stdout.

**Comment by armintoepfer** [comment]
Can you compile it on your own? If so, give the `v0.6.1` branch a try.

**Comment by ebioman** [comment]
Thanks fro the prompt answers, unfortunately I cant currently.
So far I was going via Bioconda due to lack of meson on our cluster.
Will try it on my PC later

**Comment by armintoepfer** [comment]
Latest version 0.7.0 added this as a feature/
