### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/pbmm2#8]
All the below dependencies I installed via anaconda:
meson 0.47.1
ninja 1.8.2
bzip2 1.0.6
gcc 7 
htslib

And these from bioconda:
pbbam 0.18
pbcopper  0.4.1
minimap2 2.12

All of the above seem to be picked up correctly by the meson pkg-configure based dependency system except for minimap2 which does not generate correctly the dependency file.

Meson seems to be happy except for the warning:

```bash
WARNING: Project targetting '>= 0.46.0' but tried to use feature introduced in '0.47.0': build_always_stale arg in custom_target
Configuring Pbmm2Version.cpp using configuration
Build targets in project: 8
WARNING: Project specifies a minimum meson_version '>= 0.46.0' which conflicts with:
 * 0.47.0: {'build_always_stale arg in custom_target'}
```

Ninja on the other hand results then in an error:

```bash
[28/40] Generating Pbmm2GitHash.cpp with a custom command.
FAILED: src/Pbmm2GitHash.cpp 
.....
.....
../src/AlignWorkflow.cpp:296:67:   required from here
/usr/include/boost/optional/optional.hpp:346:8: error: use of deleted function 'std::future<_Res>::future(const std::future<_Res>&) [with _Res = std::unique_ptr<std::vector<PacBio::BAM::BamRecord> >]'
        new (m_storage.address()) internal_type(val) ;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/miniconda/include/pbcopper/parallel/WorkQueue.h:10:0,
                 from ../src/AlignWorkflow.cpp:22:
/usr/local/miniconda/gcc/include/c++/future:763:7: note: declared here
       future(const future&) = delete;
       ^~~~~~
```
I attached a log if you have any idea by chance
[pbmm2.log](https://github.com/PacificBiosciences/pbmm2/files/2311736/pbmm2.log)

**Comment by armintoepfer** [comment]
Sorry, but we don't support source builds. The latest version 0.7.0 will be in bioconda soon.
